symbols = [ "BTCUSDT" ]

[accounts]

  [accounts.A1]
  master = true
  login = "ETfQB2zz61HTAA8t8rCnBflKsqANIKaYyzq8Hn6ItDqL1fiu38FZldHsqgQ1Mqu4"
  secret = "0hjyeGUGfRGqfyG86VuEXweSmmD2nUvjxY4bEeII0b6iCerAjI3pmUQIJNW6VDsH"
# drop-copy
#  login = "mtWq5uoH427w3v6uOBfPl3SGtdIPl1swj4XXht83nrGvHeYsJlUdup8HJ9gRwtHs"
#  secret = "FAqRRoU4YZDJntUwB1qA9KO3mjjdwNBXBpAlQmyQcEJjv17ypK2aRthUgTrUk6nL"
  symbols = ".*"

[templates]

  [templates.create_order]

    [templates.create_order.ET]
    self_trade_prevention_mode = "EXPIRE_TAKER"

    [templates.create_order.EM]
    self_trade_prevention_mode = "EXPIRE_MAKER"

    [templates.create_order.EB]
    self_trade_prevention_mode = "EXPIRE_BOTH"
  
  [templates.cancel_order]

    [templates.cancel_order.ON]
    cancel_restrictions = "ONLY_NEW"

    [templates.cancel_order.OPF]
    cancel_restrictions = "ONLY_PARTIALLY_FILLED"
  
[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*" ]

[rate_limits]

  [rate_limits.global]
    type = "ORDER_ACTION"
    aggregate = true
    request_limit = 100
    monitor_period = "10s"
    ban_period = "5m"

  [rate_limits.A1]
    type = "CREATE_ORDER"
    accounts = "A.*"
    request_limit = 30
    monitor_period = "1s"
    ban_period = "5m"

  [rate_limits.market_maker]
    type = "CREATE_ORDER"
    users = [ "trader" ]
    request_limit = 20
    monitor_period = "200ms"
    ban_period = "5m"
